exclude: "src/sylvie/_ast_based/" # still not implemented
repos:
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        args: [--line-length=80, --experimental-string-processing]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [--max-line-length=80]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.2
    hooks:
      - id: isort
        args: [--profile=black, -l=80]

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args:
          [
            --convention=google,
            --ignore-decorators=staticmethod,
            classmethod,
            --verbose,
            --source,
            --explain,
          ]
