repos:
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        args: [--line-length=79, --experimental-string-processing]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [--format=black]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.2
    hooks:
      - id: isort
        args: [--profile="black", --src_paths="src/", --line_length=79]

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args:
          [
            --convention="google",
            --ignore-decorators="staticmethod",
            --verbose,
            --source,
            --explain,
          ]
