name: Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip3 install -r requirements.txt && pip3 install -e .

      - name: Build and Commit
        run: |
          mkdir -p docs/html
          sphinx-apidoc -fePM -o docs src/sylvie
          sphinx-build -a -b html docs docs/_build
          cd docs && make html && cd _build/html
          git config --local user.email "dev.aditya.alok+sylvie+github+actions@gmail.com"
          git config --local user.name "sylvie-github-actions[bot]"
          git add .
          git commit -m "docs: add changes for $(git rev-parse --short ${GITHUB_SHA})"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: docs/_build/html
